version: '3.9'

services:
  api:
    build:
      context: .
      args:
        DJANGO_SUPERUSER_PASSWORD: $DJANGO_SUPERUSER_PASSWORD
        DJANGO_SUPERUSER_EMAIL: $DJANGO_SUPERUSER_EMAIL
        DJANGO_SUPERUSER_USERNAME: $DJANGO_SUPERUSER_USERNAME
    ports:
      - "${DJANGO_PORT}:8000"
